# Generated by Django 4.2.20 on 2025-03-14 15:47

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the event', max_length=255)),
                ('description', models.TextField(help_text='Description of the event')),
                ('read_more_url', models.URLField(blank=True, help_text='Optional URL for more details', null=True)),
            ],
            options={
                'verbose_name': 'Upcoming Event',
                'verbose_name_plural': 'Upcoming Events',
            },
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('video', 4), ('image', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title of the video', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short description of the video', 'required': False}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Upload a video file'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional custom icon for the video', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('file', 2), ('icon', 3)]], {'icon': 'media', 'label': 'Video'}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title of the image', 'required': True}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short description of the image', 'required': False}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': 'Image'}), 8: ('wagtail.blocks.StructBlock', [[('title', 5), ('description', 6), ('image', 7)]], {'icon': 'image', 'label': 'Image'})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Description of the content.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Short introduction.'),
        ),
    ]
