# Generated by Django 4.2.20 on 2025-03-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_upcomingevent_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpcomingEvent',
        ),
    ]
