# Generated by Django 4.2.20 on 2025-03-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_upcomingevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='content',
        ),
    ]
