# Generated by Django 4.2.19 on 2025-02-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_blog_profile_blogmedia_relationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
