# Generated by Django 4.2.19 on 2025-02-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_profile_is_paid_profile_like_count_profile_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="liked_profiles",
            field=models.ManyToManyField(related_name="liked_by", to="core.profile"),
        ),
    ]
