# Generated by Django 4.2.19 on 2025-02-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_profile_liked_profiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="liked_profiles",
            field=models.ManyToManyField(
                blank=True, related_name="liked_by", to="core.profile"
            ),
        ),
    ]
