# Generated by Django 4.2.20 on 2025-03-25 07:06

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True, help_text='Short introduction to the event page.')),
                ('content', wagtail.fields.StreamField([('event', 4), ('video', 8), ('image', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Event title', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short description of the event', 'required': False}), 2: ('wagtail.blocks.DateBlock', (), {'help_text': 'Event date'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Event location', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('date', 2), ('location', 3)]], {'icon': 'date', 'label': 'Event'}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title of the video', 'required': True}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short description of the video', 'required': False}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Upload a video file'}), 8: ('wagtail.blocks.StructBlock', [[('title', 5), ('description', 6), ('file', 7)]], {'icon': 'media', 'label': 'Video'}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title of the image', 'required': True}), 10: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short description of the image', 'required': False}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': 'Image'}), 12: ('wagtail.blocks.StructBlock', [[('title', 9), ('description', 10), ('image', 11)]], {'icon': 'image', 'label': 'Image'})})),
            ],
            options={
                'verbose_name': 'Upcoming Event Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
